name: Build, scan, and publish to GitHub Container Registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-scan-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---------- set lowercase image name ----------
      - name: Set image name
        run: echo "IMAGE_NAME=ghcr.io/$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')/build-push-app" >> $GITHUB_ENV

      # ---------- build locally (for scanning) ----------
      - name: Build image (local, not pushed yet)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cache
          cache-to: type=inline

      # ---------- scan with Trivy ----------
      - name: Scan image with Trivy (fail on HIGH/CRITICAL)
        uses: aquasecurity/trivy-action@0.11.2
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: 'table'
          severity: 'HIGH,CRITICAL'
          output: trivy-results.txt
          exit-code: '1'

      - name: Show Trivy results (if present)
        if: always()
        run: |
          if [ -f trivy-results.txt ]; then
            echo "==== Trivy results ===="
            cat trivy-results.txt
            echo "======================="
          else
            echo "No Trivy results file found."
          fi

      # ---------- push to GHCR if scan passed ----------
      - name: Push image to GHCR
        if: ${{ success() }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cache
          cache-to: type=inline

      # ---------- show final image name ----------
      - name: Print image name
        run: |
          echo "Image pushed to:"
          echo "${IMAGE_NAME}:latest"
          echo "${IMAGE_NAME}:${GITHUB_SHA}"

